version: "3.9"

services:
  ingestion-gateway:
    image: ${INGESTION_IMAGE}
    container_name: ingestion-gateway
    env_file:
      - .env
    ports:
      - "8002:8000"
    volumes:
      - /root/automations/data_input:/shared/input
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    user: "50000:0"
    
